plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.ferra13671'
version = '1.0'

def osName = providers.systemProperty("os.name").get().toLowerCase()
def osArch = providers.systemProperty("os.arch").get().toLowerCase()

if (osName.startsWith("linux")) {
    project.ext.lwjglNatives = "natives-linux"
    if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
        project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
    } else if  (osArch.startsWith("ppc")) {
        project.ext.lwjglNatives += "-ppc64le"
    } else if  (osArch.startsWith("riscv")) {
        project.ext.lwjglNatives += "-riscv64"
    }
}
if (osName.startsWith("mac") || osName.startsWith("darwin")) {
    project.ext.lwjglNatives = "natives-macos"
    if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
        project.ext.lwjglNatives += "-arm64"
    }
}
if (osName.startsWith("windows")) {
    project.ext.lwjglNatives = "natives-windows"
    if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
        project.ext.lwjglNatives += "-arm64"
    }
}

repositories {
    mavenCentral()
}

sourceSets {
    example {
        compileClasspath += main.compileClasspath
        runtimeClasspath += main.runtimeClasspath
    }
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.joml:joml:${jomlVersion}"

    runtimeOnly "org.lwjgl:lwjgl::${project.ext.lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-openal::${project.ext.lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-stb::${project.ext.lwjglNatives}"

    compileOnly("org.projectlombok:lombok:${project.lombok_version}")
    annotationProcessor("org.projectlombok:lombok:${project.lombok_version}")

    compileOnly "org.apiguardian:apiguardian-api:${apiguardian_version}"

    exampleImplementation sourceSets.main.output

    exampleCompileOnly("org.projectlombok:lombok:${project.lombok_version}")
    exampleAnnotationProcessor("org.projectlombok:lombok:${project.lombok_version}")
}

java {
    withSourcesJar()
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.ferra13671'
            artifactId = "overtone"
            artifact source: jar.archiveFile, classifier: null
            artifact sourcesJar
        }
    }

    repositories {
        mavenLocal()
    }
}